apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: leo-liu-react-next-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
    - name: pipeline-env-shared-data
      description: |
        This workspace stores the data mainly for gitops environment files of workloads
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: quay.io/leoliu2011/react-next-app
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/leo-liu-nextjs-app
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: install-dependencies
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: ARGS
          value:
            - clean-install
      runAfter:
        - clone-repository
    # - name: run-tests
    #   taskRef:
    #     name: npm
    #   workspaces:
    #     - name: source
    #       workspace: pipeline-shared-data
    #   params:
    #     - name: ARGS
    #       value:
    #         - test
    #   runAfter:
    #     - install-dependencies
    - name: build-image
      runAfter:
        - install-dependencies
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: kustomize-build
      runAfter:
        - build-image
      params:
        - name: image-with-tag
          value: "$(params.image-repo)=$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: test-deploy
      runAfter:
        - kustomize-build
      params:
        - name: app-namespace
          value: leo-liu-pipeline-from-scratch
        - name: app-name
          value: kisoong-leo-assignment
      taskRef:
        kind: Task
        name: test-deploy
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: clone-env-repository
      runAfter: 
        - test-deploy
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/leo-liu-nextjs-app-gitops.git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-env-shared-data
    - name: upload-environment
      runAfter:
        - clone-env-repository
      params:
        - name: GIT_USER_NAME
          value: yliu138
        - name: GIT_USER_EMAIL
          value: yliu1382011@gmail.com
        - name: GIT_SCRIPT
          value: |
            mkdir -p prod
            cp /workspace/input/k8s/manifests.yaml prod/manifests.yaml
            git add ./prod/manifests.yaml
            git commit -m "Triggered by pipeline $(tasks.clone-repository.results.commit), and updated manifests.yaml"
            echo "Current branch: $(git branch)"
            git push origin HEAD:master
      taskRef:
        kind: Task
        name: git-cli
      workspaces:
        - name: source
          workspace: pipeline-env-shared-data
        - name: input
          workspace: pipeline-shared-data