apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: llpfs-live-leo-liu-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: leo-liu-react-next-pipeline
  workspaces:
    - name: pipeline-env-shared-data
      persistentVolumeClaim:
        claimName: leo-liu-live-pvc-gid-rwx-2
    - name: pipeline-shared-data
      persistentVolumeClaim:
        # claimName: leo-liu-live-pvc-2nd
        claimName: leo-liu-live-pvc-gid-rwx
      # volumeClaimTemplate:
      #   spec:
      #     accessModes:
      #       - ReadWriteOnce
      #     resources:
      #       requests:
      #         storage: 1Gi