apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: kisoong-leo-fps
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: leo-liu-pipeline-react-next-pipeline-triggerbinding
      template:
        name: leo-liu-pipeline-react-next-triggertemplate