apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: leo-liu-pipeline-react-next-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: leo-liu-pipeline-react-next-pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: leo-liu-react-next-pipeline
        workspaces:
          - name: pipeline-shared-data
            persistentVolumeClaim:
              claimName: leo-liu-live-pvc-gid-rwx
            # volumeClaimTemplate:
            #   spec:
            #     accessModes:
            #       - ReadWriteOnce
            #     resources:
            #       requests:
            #         storage: 1Gi