apiVersion: v1
kind: Service
metadata:
  annotations:
    enzo: "true"
  labels:
    app: leo-liu-assignment
    app.kubernetes.io/instance: leo-liu-assignment
    app.kubernetes.io/name: leo-liu-assignment
  name: leo-liu-assignment
  namespace: leo-liu-pipeline-from-scratch
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: leo-liu-assignment
    app.kubernetes.io/name: leo-liu-assignment
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f7580aa1eb6f7176705176e201ecff4de93edafb
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/leo-liu-nextjs-app
    enzo: "true"
  labels:
    app: leo-liu-assignment
    app.kubernetes.io/instance: leo-liu-assignment
    app.kubernetes.io/name: leo-liu-assignment
    app.openshift.io/runtime: js
  name: leo-liu-assignment
  namespace: leo-liu-pipeline-from-scratch
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: leo-liu-assignment
      app.kubernetes.io/name: leo-liu-assignment
  template:
    metadata:
      annotations:
        enzo: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: leo-liu-assignment
        app.kubernetes.io/name: leo-liu-assignment
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/leoliu2011/react-next-app:22a968e4a40b92f476be03b110b9092f60b4b287
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: leo-liu-assignment
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    enzo: "true"
  name: llpfs
  namespace: leo-liu-pipeline-from-scratch
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: leo-liu-assignment
    weight: 100
  wildcardPolicy: None
